jobs:
- substitutions:
  - type: string
    find: foo
    replace: bar
  - type: regex
    find: "(a)(b)(c)"
    replace: "$3$2$1"
  mappings:
  - source:
      type: http
      url: https://example.com/file.txt
    destination:
      type: BucketObject
      path: gs://example-bucket-name/file.txt
